name:                puzzle1-q04
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/puzzle1-q04#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  puzzle1-q04:
    source-dirs:      src
    main:             Main.hs
